fullnameOverride: postgres
postgresqlDatabase: otuslab
postgresqlUsername: user
postgresqlPassword: password

service:
  type: NodePort
  port: 5432
  nodePort: 31841

persistence:
  enabled: true
  size: 512Mi

resources:
  requests:
    memory: 1Gi
    cpu: "1"