apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appservice.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "appservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "appservice.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: POSTGRES_HOST
              valueFrom: 
                configMapKeyRef:
                  name: user-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: user-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: POSTGRES_PASSWORD
          livenessProbe:
            httpGet:
              port: 80
              path: /health
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              port: 80
              path: /health
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 3