apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
data:
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc }}
