apiVersion: v1
kind: Service
metadata:
  name: {{ include "appservice.fullname" . }}
spec:
  selector:
    {{- include "appservice.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  type: ClusterIP
